package app.hushmessenger.extension;

/** Complete Vietnamese text for the settings UI. */
final class SettingsTextVi {
    private SettingsTextVi() { }

    static final String[][] TEXT = {
        {"controls", "Chức năng"},
        {"app", "Ứng dụng"},
        {"all", "Tất cả"},
        {"inbox", "Hộp thư"},
        {"chats", "Đoạn chat"},
        {"more", "Thêm"},
        {"navigation", "Điều hướng"},
        {"stickers", "Nhãn dán"},
        {"conversations", "Cuộc trò chuyện"},
        {"links_bubbles", "Liên kết và bong bóng chat"},
        {"privacy", "Quyền riêng tư"},
        {"theme", "Giao diện"},
        {"settings", "Cài đặt HushMessenger"},
        {"preview_title", "Bản xem trước giao diện HushMessenger"},
        {"preview_notice", "Đây là bản xem trước giao diện. Các công tắc này không thay đổi Messenger."},
        {"tagline", "Biến Messenger thành của riêng bạn."},
        {"open", "Mở"},
        {"open_messenger", "Mở Messenger"},
        {"reopen", "Áp dụng thay đổi trong hộp thư bằng cách chọn Ứng dụng > Khởi động lại Messenger."},
        {"quick_access", "TRUY CẬP NHANH"},
        {"access_help", "Nhấn giữ biểu tượng Messenger trên màn hình chính để mở Chức năng bản vá hoặc Khởi động lại Messenger. Bạn cũng có thể mở cài đặt HushMessenger từ danh sách ứng dụng."},
        {"hide_drawer_icon", "Ẩn biểu tượng trong danh sách ứng dụng"},
        {"hide_drawer_icon_help", "Xóa cài đặt HushMessenger khỏi danh sách ứng dụng. Hãy mở từ tab Menu hoặc menu bên của Messenger, hoặc nhấn giữ biểu tượng Messenger trên màn hình chính rồi chọn Chức năng bản vá."},
        {"shared_install_help", "Biểu tượng cài đặt thuộc về Messenger. Gỡ một trong hai biểu tượng sẽ xóa Messenger và dữ liệu cục bộ. Dùng Ẩn biểu tượng trong danh sách ứng dụng để chỉ ẩn mục này."},
        {"access_help_hosted", "Nhấn giữ biểu tượng Messenger trên màn hình chính để mở Chức năng bản vá hoặc Khởi động lại Messenger. Bản cài đặt Root Mount không có biểu tượng cài đặt riêng trong danh sách ứng dụng."},
        {"access_help_hosted_menu", "Nhấn giữ biểu tượng Messenger trên màn hình chính để mở Chức năng bản vá hoặc Khởi động lại Messenger, hoặc mở cài đặt HushMessenger từ mục tương ứng trong tab Menu hay menu bên của Messenger. Bản cài đặt Root Mount không có biểu tượng cài đặt riêng trong danh sách ứng dụng."},
        {"access_help_menu", "Nhấn giữ biểu tượng Messenger trên màn hình chính để mở Chức năng bản vá hoặc Khởi động lại Messenger. Bạn cũng có thể mở cài đặt HushMessenger từ mục tương ứng trong tab Menu, menu bên của Messenger hoặc danh sách ứng dụng."},
        {"access_help_missing", "Nhấn giữ biểu tượng Messenger trên màn hình chính để mở Chức năng bản vá hoặc Khởi động lại Messenger. Gói này không có biểu tượng cài đặt trong danh sách ứng dụng."},
        {"access_help_missing_menu", "Mở HushMessenger từ tab Menu hoặc menu bên của Messenger, hoặc nhấn giữ biểu tượng Messenger trên màn hình chính để mở Chức năng bản vá hay Khởi động lại Messenger. Gói này không có biểu tượng cài đặt trong danh sách ứng dụng."},
        {"drawer_search", "Cài đặt biểu tượng trong danh sách ứng dụng"},
        {"drawer_root", "Không cần ẩn biểu tượng trên Root Mount vì không có biểu tượng cài đặt riêng để ẩn."},
        {"drawer_missing", "Không thể ẩn biểu tượng vì gói này không có alias trình khởi chạy cho phần cài đặt."},
        {"drawer_requires_menu", "Muốn ẩn biểu tượng, HushMessenger phải có mục trong tab Menu hoặc menu bên của Messenger. Biểu tượng sẽ vẫn hiện nếu lối tắt là cách truy cập duy nhất còn lại."},
        {"restart", "Khởi động lại Messenger"},
        {"patch_controls", "Chức năng bản vá"},
        {"restarting", "Đang khởi động lại Messenger..."},
        {"restart_unavailable", "Không thể khởi động lại. Hãy đóng Messenger rồi mở lại từ danh sách ứng dụng."},
        {"settings_open_failed", "Không thể mở cài đặt HushMessenger. Hãy nhấn giữ biểu tượng Messenger trên màn hình chính rồi thử chọn Chức năng bản vá."},
        {"restart_save_failed", "Không thể lưu lựa chọn nên Messenger chưa được khởi động lại. Hãy thử lại."},
        {"setup", "THIẾT LẬP CỦA BẠN"},
        {"paused", "Tạm dừng mọi thay đổi"},
        {"search", "Tìm chức năng"},
        {"empty_title", "Tìm chức năng bạn cần"},
        {"empty_help", "Hãy thử từ khóa hoặc danh mục khác. Chỉ các bản vá có trong bản cài đặt này mới xuất hiện."},
        {"clear", "Xóa bộ lọc"},
        {"unavailable", "Không khả dụng trên phiên bản Android này. Lựa chọn của bạn vẫn được giữ lại."},
        {"bubble_stock", "Mặc định"},
        {"bubble_chat_heads", "Chat Heads"},
        {"bubble_native", "Native Bubbles"},
        {"bubble_changed", "Đã chọn %s. Hãy khởi động lại Messenger để áp dụng."},
        {"bubble_help", "Mặc định để Messenger tự quyết định. Chat Heads còn cần bật công tắc Chat heads của Messenger và cấp quyền hiển thị trên ứng dụng khác. Với Native Bubbles, hãy dùng phần cài đặt bong bóng Android bên dưới để cho phép bong bóng của Messenger. Quyền thông báo và khả năng hỗ trợ của tài khoản vẫn được áp dụng. Tài khoản không được hỗ trợ sẽ tiếp tục dùng cách mặc định của Messenger. Tạm dừng mọi thay đổi sẽ khôi phục cách mặc định."},
        {"bubble_unsupported", "Gói này chưa có luồng Native Bubbles đã được xác minh. Messenger tiếp tục hoạt động theo mặc định và lựa chọn đã lưu của bạn vẫn được giữ lại."},
        {"bubble_permissions", "Cài đặt bong bóng Android"},
        {"bubble_notifications", "Cài đặt thông báo Messenger"},
        {"bubble_conversations", "Cài đặt cuộc trò chuyện Android"},
        {"bubble_settings_missing", "Điện thoại này không có màn hình cài đặt phù hợp. Hãy mở thông tin ứng dụng Messenger rồi chọn Thông báo."},
        {"experimental", "Thử nghiệm"},
        {"choice_on", "Đã bật %s"},
        {"choice_off", "Đã tắt %s"},
        {"appearance", "GIAO DIỆN"},
        {"light", "Giao diện sáng"},
        {"light_help", "Dùng nền sáng trong phần cài đặt."},
        {"theme_help", "Mặc định là giao diện tối. Lựa chọn của bạn sẽ được lưu."},
        {"about", "GIỚI THIỆU HUSHMESSENGER"},
        {"version", "Phiên bản"},
        {"installed", "Chức năng đã cài đặt"},
        {"copy", "Sao chép thiết lập"},
        {"copy_help", "Sao chép phiên bản ứng dụng và lựa chọn chức năng. Không gồm thông tin tài khoản hay đoạn chat và không gửi dữ liệu đi đâu."},
        {"setup_activity_help", "Nhật ký hoạt động cho biết một chức năng đã chạy, nhưng không xác nhận hiệu quả hiển thị hoặc mức bảo vệ quyền riêng tư của chức năng đó."},
        {"usage", "SỬ DỤNG CÁC CHỨC NĂNG"},
        {"save_help", "Các thay đổi được lưu ngay. Hãy dùng Khởi động lại Messenger sau khi đổi chức năng hộp thư. Tài khoản của bạn vẫn được đăng nhập."},
        {"pause_help", "Tạm dừng sẽ giữ lại lựa chọn của bạn và tạm thời khôi phục cách hoạt động mặc định."},
        {"account_help", "Lựa chọn của bạn áp dụng cho mọi tài khoản Messenger trong bản cài đặt này."},
        {"missing", "Không thấy một chức năng?"},
        {"missing_help", "Hãy chọn chức năng đó trong Morphe rồi dựng lại Messenger. Chỉ cập nhật mã nguồn sẽ không cài thêm chức năng mới."},
        {"source", "Mã nguồn và giấy phép"},
        {"no_browser", "Không có trình duyệt khả dụng"},
        {"credits", "GPL-3.0. Có sử dụng đóng góp từ De-Vanced, ReVanced, Doom và Messenger Cleaner."},
        {"independent", "Độc lập với Meta và Morphe."},
        {"clipboard", "Thiết lập HushMessenger"},
        {"copied", "Đã sao chép thiết lập"},
        {"copy_failed", "Không thể sao chép thiết lập. Hãy thử lại."},
        {"export", "Xuất lựa chọn"},
        {"export_help", "Sao chép các lựa chọn chức năng vào bộ nhớ tạm. Dán chúng vào mục Nhập của bản cài đặt khác để khôi phục."},
        {"exported", "Đã xuất lựa chọn"},
        {"export_failed", "Không thể xuất. Hãy thử lại."},
        {"import_choices", "Nhập lựa chọn"},
        {"import_help", "Đọc các lựa chọn từ bộ nhớ tạm. Trước tiên hãy sao chép một bản xuất."},
        {"imported_one", "Đã khôi phục %d lựa chọn"},
        {"imported_many", "Đã khôi phục %d lựa chọn"},
        {"import_empty", "Không có gì để nhập. Hãy xuất lựa chọn trước rồi dán vào đây."},
        {"import_invalid", "Đây không phải bản sao lưu HushMessenger hợp lệ. Hãy dùng nguyên trạng tệp xuất lựa chọn có dung lượng không quá 16 KiB."},
        {"import_unknown_one", "Đã bỏ qua %d lựa chọn không xác định."},
        {"import_unknown_many", "Đã bỏ qua %d lựa chọn không xác định."},
        {"import_unavailable_one", "Đã bỏ qua %d lựa chọn không có trong gói này."},
        {"import_unavailable_many", "Đã bỏ qua %d lựa chọn không có trong gói này."},
        {"import_no_choices", "Không có lựa chọn nào của chức năng đã cài đặt để khôi phục."},
        {"save_choices_file", "Lưu lựa chọn vào tệp"},
        {"read_choices_file", "Khôi phục lựa chọn từ tệp"},
        {"choices_file_help", "Chỉ gồm cài đặt, tối đa 16 KiB. Đoạn chat, tài khoản và dữ liệu khôi phục không được đưa vào. Lựa chọn bị lược bỏ hoặc không khả dụng vẫn giữ giá trị đã lưu. Hãy chọn lại tệp nếu phần cài đặt mở lại."},
        {"choices_file_saved", "Đã lưu tệp lựa chọn"},
        {"choices_file_saving", "Đang lưu tệp lựa chọn..."},
        {"choices_file_reading", "Đang đọc tệp lựa chọn..."},
        {"cancel_choices_file", "Hủy thao tác với tệp"},
        {"choices_file_canceled", "Đã hủy thao tác với tệp. Tệp đang lưu có thể chưa hoàn chỉnh."},
        {"choices_file_timeout", "Thao tác với tệp mất quá nhiều thời gian. Hãy thử lại. Tệp đang lưu có thể chưa hoàn chỉnh."},
        {"choices_file_busy", "Các thao tác tệp trước đó vẫn đang hoàn tất. Hãy thử lại khi ứng dụng lưu trữ phản hồi."},
        {"choices_file_changed", "Các lựa chọn đã thay đổi trong khi tải tệp. Hãy khôi phục lại tệp để thay thế chúng."},
        {"check_updates", "Kiểm tra bản cập nhật"},
        {"check_updates_help", "Kiểm tra GitHub khi được bật hoặc khi mở phần cài đặt. Kết quả đã lưu được dùng lại trong một giờ và thời gian thử lại của GitHub được tuân thủ. Mặc định tắt. GitHub nhận địa chỉ IP và siêu dữ liệu kết nối của bạn. Không có nội dung tài khoản hay đoạn chat nào được tải lên."},
        {"check_now", "Kiểm tra ngay"},
        {"update_loading", "Đang kiểm tra bản cập nhật..."},
        {"update_available", "Đã có phiên bản %s"},
        {"update_action", "Xem bản phát hành"},
        {"up_to_date", "Bạn đang dùng phiên bản mới nhất."},
        {"update_ahead", "Đã cài %s. Phiên bản mới nhất được phát hành là %s."},
        {"update_retry", "GitHub chưa thể phản hồi. Hãy thử Kiểm tra ngay sau %s."},
        {"update_error", "Không thể kiểm tra bản cập nhật."},
        {"active_now", "Vừa sử dụng"},
        {"active_ago", "Đã sử dụng cách đây %s"},
        {"seconds_short", "%d giây"},
        {"minutes_short", "%d phút"},
        {"hours_short", "%d giờ"},
        {"not_active", "Chưa có gì để thay đổi kể từ lần khởi động lại"},
        {"unsent_not_active", "Chưa ghi nhận hoạt động thu hồi tin nhắn kể từ lần khởi động lại"},
        {"unsent_history_title", "Lịch sử tin nhắn đã thu hồi"},
        {"unsent_history_entry_help", "Xem các tin nhắn đã được lưu cục bộ trên thiết bị này và sau đó được Messenger báo là đã thu hồi."},
        {"unsent_history_help", "Chỉ lưu trên thiết bị này. Một mục có thể không có nội dung nếu Messenger thu hồi trước khi HushMessenger kịp lưu văn bản gốc."},
        {"unsent_history_diagnostics", "Hook nhận tin: %d, đã lưu: %d • Hook thu hồi: %d, đã đánh dấu: %d"},
        {"unsent_history_back", "Quay lại"},
        {"unsent_history_clear", "Xóa lịch sử"},
        {"unsent_history_clear_confirm", "Xóa toàn bộ lịch sử tin nhắn đã thu hồi được lưu cục bộ?"},
        {"unsent_history_cleared", "Đã xóa lịch sử tin nhắn thu hồi"},
        {"unsent_history_clear_failed", "Không thể xóa lịch sử tin nhắn thu hồi."},
        {"unsent_history_read_failed", "Không thể đọc lịch sử tin nhắn thu hồi."},
        {"unsent_history_empty", "Chưa ghi nhận tin nhắn đã thu hồi nào."},
        {"unsent_history_missing_text", "Không kịp lưu nội dung trước khi tin nhắn bị thu hồi."},
        {"unsent_history_unknown_sender", "Chưa xác định người gửi"},
        {"unsent_history_sender", "Người gửi: %s"},
        {"unsent_history_received_at", "Nhận lúc %s"},
        {"unsent_history_unsent_at", "Đã thu hồi lúc %s"},
        {"error_now", "Vừa dừng do lỗi"},
        {"error_ago", "Đã dừng do lỗi cách đây %s"},
        {"changes_paused", "Đã tạm dừng các thay đổi"},
        {"changes_resumed", "Đã tiếp tục các thay đổi"},
        {"safe_mode", "Chế độ an toàn"},
        {"safe_mode_help", "Messenger đã gặp sự cố nhiều lần liên tiếp nên mọi chức năng đã bị tắt. Các lựa chọn của bạn vẫn được lưu. Nhấn Tiếp tục để bật lại."},
        {"safe_mode_help_paused", "Messenger đã gặp sự cố nhiều lần liên tiếp. Các lựa chọn của bạn vẫn được lưu. Trước tiên hãy thoát chế độ an toàn. Tạm dừng mọi thay đổi sẽ vẫn bật cho đến khi bạn tắt."},
        {"resume", "Tiếp tục"},
        {"clear_safe_mode", "Thoát chế độ an toàn"},
        {"safe_mode_cleared", "Đã thoát chế độ an toàn. Các thay đổi vẫn đang tạm dừng."},
        {"safe_mode_save_failed", "Không thể lưu trạng thái chế độ an toàn. Các thay đổi vẫn tạm dừng. Hãy thử lại."},
        {"enabled_one", "Đã bật %d chức năng"},
        {"enabled_many", "Đã bật %d chức năng"},
        {"saved_one", "Đã lưu %d lựa chọn. Hãy tắt tạm dừng để tiếp tục."},
        {"saved_many", "Đã lưu %d lựa chọn. Hãy tắt tạm dừng để tiếp tục."},
        {"saved", "Các lựa chọn của bạn được lưu tự động."},
        {"none_installed", "Chưa cài chức năng tùy chọn nào. Hãy chọn các bản vá trong Morphe rồi dựng lại Messenger."},
        {"no_matches", "Không có chức năng phù hợp. Hãy thử tìm kiếm khác."},
        {"results_one", "%d/%d chức năng đã cài đặt"},
        {"results_many", "%d/%d chức năng đã cài đặt"},
        {"open_help", "Mở Messenger từ danh sách ứng dụng"},

        {"ads.title", "Ẩn quảng cáo trong hộp thư"},
        {"ads.description", "Xóa thẻ quảng cáo trong hộp thư nếu Meta đưa quảng cáo hộp thư trở lại sau khi ngừng bán loại quảng cáo này vào tháng 11 năm 2025."},
        {"people.title", "Ẩn Những người bạn có thể biết"},
        {"people.description", "Xóa người được đề xuất khỏi đoạn chat, tìm kiếm và story, cũng như khỏi tab Mọi người và Thông báo."},
        {"friend_requests.title", "Ẩn thẻ lời mời kết bạn"},
        {"friend_requests.description", "Ẩn các thẻ mà không chấp nhận hay từ chối lời mời."},
        {"community_inbox.title", "Ẩn đoạn chat cộng đồng đã tham gia"},
        {"community_inbox.description", "Ẩn đoạn chat cộng đồng đã tham gia khỏi hộp thư chính. Tìm kiếm và thư mục cộng đồng vẫn giữ chúng. Việc gửi nhận và số lượng chưa đọc không thay đổi. Thay đổi có hiệu lực khi hộp thư được hiển thị lại."},
        {"growth.title", "Ẩn lời nhắc phát triển tương tác"},
        {"growth.description", "Xóa lời nhắc thêm người, bảng gợi ý trong ghi chú như Công khai ghi chú của tôi và thẻ Chia sẻ story của bạn sau story của người khác."},
        {"inbox_promotions.title", "Ẩn quảng bá trong hộp thư"},
        {"inbox_promotions.description", "Ẩn biểu ngữ quảng bá nhanh của Messenger trong danh sách chat."},
        {"stories.title", "Ẩn story và ghi chú"},
        {"stories.description", "Xóa khay ngang phía trên các đoạn chat."},
        {"subtabs.title", "Ẩn tab trong hộp thư"},
        {"subtabs.description", "Ẩn tab Trang chủ và Kênh trong hộp thư."},
        {"facebook.title", "Ẩn lối tắt Facebook"},
        {"facebook.description", "Ẩn các nút Facebook, lối tắt hồ sơ và chia sẻ, cùng mục Cũng của Meta trong tab Menu."},
        {"meta_ai.title", "Ẩn Meta AI"},
        {"meta_ai.description", "Ẩn nút nổi, nút trên thanh công cụ, tab Meta AI, các mục menu và AI trong tìm kiếm."},
        {"moments.title", "Ẩn Chat Moments"},
        {"moments.description", "Ẩn Chat Moments khỏi menu."},
        {"reels_badge.title", "Ẩn huy hiệu Reels"},
        {"reels_badge.description", "Ẩn huy hiệu thông báo Reels."},
        {"chat_animation.title", "Trượt đoạn chat khi mở và đóng"},
        {"chat_animation.description", "Trượt đoạn chat vào từ cạnh màn hình khi mở và trượt ra khi quay lại, trong khi màn hình bên dưới đứng yên. Chat Heads và bong bóng vẫn dùng hiệu ứng riêng."},
        {"ai_stickers.title", "Ẩn công cụ nhãn dán AI"},
        {"ai_stickers.description", "Ẩn nút tạo nhãn dán AI, tab nhãn dán đã tạo và các gợi ý nhãn dán AI."},
        {"avatar_stickers.title", "Ẩn nhãn dán avatar"},
        {"avatar_stickers.description", "Ẩn tab avatar trong bàn phím nhãn dán."},
        {"chat_promotions.title", "Ẩn quảng bá trong cuộc trò chuyện"},
        {"chat_promotions.description", "Ẩn biểu ngữ quảng bá nhanh của Messenger trong cuộc trò chuyện."},
        {"suggested_replies.title", "Ẩn câu trả lời gợi ý của doanh nghiệp"},
        {"suggested_replies.description", "Ẩn câu trả lời gợi ý trong cuộc trò chuyện với doanh nghiệp."},
        {"business_suggestions.title", "Ẩn gợi ý nhập liệu của doanh nghiệp"},
        {"business_suggestions.description", "Ẩn gợi ý của doanh nghiệp khi bạn nhập."},
        {"event_prompts.title", "Ẩn lời nhắc sự kiện"},
        {"event_prompts.description", "Ẩn lời nhắc quảng bá nhanh về sự kiện trong đoạn chat."},
        {"typing.title", "Ẩn trạng thái đang nhập"},
        {"typing.description", "Ngừng gửi tín hiệu bạn đang nhập, kể cả trong đoạn chat mã hóa đầu cuối."},
        {"use_system_emoji.title", "Dùng emoji hệ thống"},
        {"use_system_emoji.description", "Hiển thị emoji bằng phông chữ của điện thoại thay cho bộ emoji tích hợp của Messenger."},
        {"original_photo.title", "Gửi ảnh chất lượng gốc"},
        {"original_photo.description", "Khi bật HD, gửi dữ liệu ảnh JPEG gốc thay vì bản được Messenger mã hóa lại. Siêu dữ liệu như vị trí và thông tin máy ảnh vẫn bị loại bỏ như trên bản của Messenger, ngoại trừ thẻ dùng để xoay ảnh đúng chiều. Ảnh trên 20 MB và video vẫn bị Messenger nén."},
        {"external_browser.title", "Mở liên kết bằng trình duyệt ngoài"},
        {"external_browser.description", "Dùng trình duyệt mặc định cho liên kết HTTP và HTTPS. Các loại liên kết khác vẫn giữ cách hoạt động ban đầu."},
        {"bubbles.title", "Cho phép bong bóng chat"},
        {"bubbles.description", "Chọn Mặc định, Chat Heads hoặc Native Bubbles bên dưới. Native Bubbles cần Android 11, tài khoản được hỗ trợ và quyền thông báo. Hãy khởi động lại Messenger sau khi đổi chế độ."},
        {"allow_screenshot.title", "Cho phép chụp màn hình"},
        {"allow_screenshot.description", "Cho phép chụp nội dung chat được bảo vệ, gồm nội dung chỉ xem một lần và Quicksnap, đồng thời ngăn thông báo chụp màn hình. Chức năng này không thêm khả năng xem lại hay lưu."},
        {"hide_read_receipts.title", "Ẩn trạng thái đã xem"},
        {"hide_read_receipts.description", "Ngừng gửi xác nhận đã xem. Đoạn chat mã hóa đã mở có thể vẫn được đánh dấu chưa đọc trên điện thoại này. Việc trả lời hoặc tắt chức năng có thể thông báo cho người gửi. Phạm vi hỗ trợ nhóm chưa được xác minh."},
        {"keep_unsent.title", "Lịch sử tin nhắn đã thu hồi"},
        {"keep_unsent.description", "Lưu bản sao văn bản cục bộ khi HushMessenger quan sát được tin nhắn trên luồng nhận hoặc hiển thị đã xác minh, rồi đánh dấu bản ghi đó khi Messenger báo thu hồi. Messenger vẫn thu hồi tin nhắn theo cách mặc định; HushMessenger không chặn hoặc thay đổi trạng thái thu hồi. Hiện chỉ một luồng E2EE trên Messenger 580 bản 346013370 đã được xác minh; media và phạm vi nhóm chưa được xác minh."},
        {"anonymous_stories.title", "Xem story mà không hiện danh tính"},
        {"anonymous_stories.description", "Mở story của người khác mà không thêm bạn vào danh sách người xem. Story được mở theo cách này vẫn được đánh dấu là đã xem ở phía bạn."},
        {"save_stories.title", "Lưu story của người khác"},
        {"save_stories.description", "Thêm mục Lưu vào menu Tùy chọn khác trên story của người khác. Ảnh hoặc video được lưu vào điện thoại giống như cách Messenger lưu story của chính bạn."},
        {"material_you.title", "Giao diện Material You"},
        {"material_you.description", "Phối màu chế độ tối của Messenger theo màu Android lấy từ hình nền trên Android 12 trở lên. Android 11 dùng bảng màu xanh dương cố định. Trước tiên hãy bật chế độ tối trong Messenger."},
    };
}
